sudo: false

language: java

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

env:
  global:
  # taken first download mirror from http://maven.apache.org/
    - BASEURL=http://mirror.softaculous.com/apache/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.tar.gz
    - FILE=apache-maven-VERSION-bin.tar.gz
    - DIR=apache-maven-VERSION/bin

matrix:
  include:
    # Open jdk 8 mvn 3.2.5
    - jdk: openjdk8
      env: VERSION=3.3.9

    # Java 8 mvn 3.3.9
    - jdk: oraclejdk8
      env: VERSION=3.3.9
    
    # Java 9 mvn 3.5.3
    - jdk: oraclejdk9
      env: VERSION=3.5.3

    # Java 10 mvn 3.5.3
    - env: JDK='JDK 10' TARGET='-Pjava10' VERSION=3.5.3
      install: . ./install-jdk.sh -F 10 -L GPL

script:
  - wget $(echo -n $BASEURL | sed -e 's#VERSION#'$VERSION'#g')
  - tar -xvzf $(echo -n $FILE | sed -e 's#VERSION#'$VERSION'#')
  - export PATH=$(echo -n $DIR | sed -e 's#VERSION#'$VERSION'#'):$PATH
  - mvn clean verify
